package chess.domain.state;

public enum GameStatus {
    ONGOING,

    CHECKMATE_WHITE_WIN,
    CHECKMATE_BLACK_WIN,
    RESIGNATION_WHITE_WIN,
    RESIGNATION_BLACK_WIN,

    STALEMATE_DRAW,
    INSUFFICIENT_MATERIAL_DRAW,
    FIFTY_MOVE_RULE_DRAW,
    REPETITION_DRAW,
    AGREEMENT_DRAW;
}